test: use false instead of /usr/bin/false
On Debian systems false is located at /bin/false (coreutils package).
This fixes unit test failure on Debian system:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/false'
/usr/lib/python3.10/subprocess.py:1845: FileNotFoundError